on:
  workflow_call:
    inputs:
      flags:
        required: true
        type: string
      test-files:
        required: true
        type: string
      destination:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ ubuntu-latest ]
        node: [ 20 ]
        include:
          - os: ubuntu-latest
            node: 18
          - os: ubuntu-latest
            node: 22
      fail-fast: false

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: "1.1.27"

      - name: Download Bati CLI
        uses: actions/download-artifact@v4
        with:
          name: bati-cli-${{ matrix.os }}-${{ matrix.node }}
          path: ./bati-cli

      - name: Download Bati tests
        uses: actions/download-artifact@v4
        with:
          name: bati-tests-${{ matrix.os }}-${{ matrix.node }}
          path: ./bati-tests

      - name: Download tests-utils
        uses: actions/download-artifact@v4
        with:
          name: tests-utils-${{ matrix.os }}-${{ matrix.node }}
          path: ./bati-tests-utils

      - name: Download tests-files
        uses: actions/download-artifact@v4
        with:
          name: tests-files-${{ matrix.os }}-${{ matrix.node }}
          path: ./bati-tests-files

      - name: Run all tests tests
        uses: ./.github/actions/bati-run
        with:
          os: ${{ matrix.os }}
          node: ${{ matrix.node }}
          flags: ${{ inputs.flags }}
          test-files: ${{ inputs.test-files }}
          destination: ${{ inputs.destination }}
