on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      flags:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: "1.1.24"

      - name: Download Bati CLI
        uses: actions/download-artifact@v4
        with:
          name: bati-cli
          path: ${{ runner.temp }}/bati-cli

      - name: Run Bati CLI
        run: bun ${{ runner.temp }}/bati-cli/dist/index.js ${{ inputs.flags }} --force .

      - name: Download tests-utils
        uses: actions/download-artifact@v4
        with:
          name: tests-utils

      - name: Setup Bati tests
        run: 

      - name: Run build
        run: turbo run build

      - name: Run tests
        run: turbo run test --only
        env:
          TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          TEST_AUTH0_ISSUER_BASE_URL: ${{ secrets.TEST_AUTH0_ISSUER_BASE_URL }}
          TEST_FIREBASE_ACCOUNT: ${{ secrets.TEST_FIREBASE_ACCOUNT }}
          TEST_FIREBASE_USER_UID: ${{ secrets.TEST_FIREBASE_USER_UID }}
          TEST_GITHUB_CLIENT_ID: ${{ secrets.TEST_GITHUB_CLIENT_ID }}
          TEST_GITHUB_CLIENT_SECRET: ${{ secrets.TEST_GITHUB_CLIENT_SECRET }}

      - name: Run lint
        run: turbo run lint --only

      - name: Run typecheck
        run: turbo run typecheck --only
