on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: testing CI
        run: echo ${{ inputs.runs-on }} ${{ inputs.working-directory }}

